In [1]:
import torch

In [2]:
a = torch.linspace(-100,100,10)
a

tensor([-100.0000,  -77.7778,  -55.5556,  -33.3333,  -11.1111,   11.1111,
          33.3333,   55.5555,   77.7778,  100.0000])

In [3]:
torch.sigmoid(a)

tensor([0.0000e+00, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 9.9999e-01,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])

In [4]:
a = torch.linspace(-1,1,10)
a

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [5]:
torch.tanh(a)

tensor([-0.7616, -0.6514, -0.5047, -0.3215, -0.1107,  0.1107,  0.3215,  0.5047,
         0.6514,  0.7616])

In [6]:
from torch.nn import functional as F

In [8]:
a = torch.linspace(-1,1,10)
a

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [9]:
torch.relu(a)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])

In [10]:
F.relu(a)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])

In [15]:
x = torch.ones(1)
w = torch.full([1],2)

In [17]:
#(1*2-1)**2=1
mse = F.mse_loss(input=x*w,target=torch.ones(1))
mse

tensor(1.)

In [18]:
torch.autograd.grad(mse,[w])

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [19]:
w.requires_grad_()

tensor([2.], requires_grad=True)

In [20]:
#w更新了动态图没更新
torch.autograd.grad(mse,[w])

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [26]:
mse = F.mse_loss(x*w,torch.ones(1))

In [22]:
torch.autograd.grad(mse,[w])#mse = (1-x*w)**2  d(mse)=2(1-x*w)*(-x)=2(1-1*2)*(-1)=2

(tensor([2.]),)

In [27]:
mse.backward()

In [28]:
w.grad

tensor([2.])

In [43]:
from torch.nn import functional as F

In [44]:
a = torch.rand(3)
a.requires_grad_()

tensor([0.1010, 0.7280, 0.1771], requires_grad=True)

In [54]:
p = F.softmax(a,dim=0)

In [55]:
torch.autograd.grad(p[1],[a],retain_graph=True)

(tensor([-0.1199,  0.2493, -0.1294]),)

In [56]:
torch.autograd.grad(p[2],[a],retain_graph=True)

(tensor([-0.0691, -0.1294,  0.1985]),)

In [52]:
p[1].backward()