In [ ]:
import torch

In [63]:
a = torch.randn(2,3)
print(a)
print(a.type())
isinstance(a,torch.FloatTensor)


tensor([[ 0.7360,  0.2314, -0.3472],
        [-0.6704, -0.6843, -0.5945]])

torch.FloatTensor

True

In [11]:
torch.tensor(1.)
a= torch.tensor(1.2)

In [12]:
len(a.shape)

0

In [13]:
torch.tensor([1.1])

tensor([1.1000])

In [15]:
torch.tensor([1.1,2.2])

tensor([1.1000, 2.2000])

In [16]:
#随机生成0维一个数字
torch.FloatTensor(1)

tensor([1.4013e-45])

In [17]:
#随机生成一维2个数字
torch.FloatTensor(2)

tensor([1.4013e-45, 0.0000e+00])

In [22]:
import  numpy as np
data = np.ones(2)
print(data)

[1. 1.]

In [26]:
torch_data = torch.from_numpy(data)
print(torch_data )

tensor([1., 1.], dtype=torch.float64)

In [43]:
a = torch.ones(2)
print(a)
print("a.shape:",a.shape)
print("len(a.shape)",len(a.shape))

tensor([1., 1.])

a.shape:

torch.Size([2])

len(a.shape)

1

In [42]:
print("a.size():",a.size())
print("len(a.size()):",len(a.size()))

a.size():

torch.Size([2])

len(a.size()):

1

In [48]:
b = [[1,1],[2,2]]
bb = np.asarray(b)
print(bb)

[[1 1]
 [2 2]]

In [49]:
bbb = torch.from_numpy(bb)
print(bbb.size())

torch.Size([2, 2])

In [50]:
print(bbb.shape)

torch.Size([2, 2])

In [51]:
print(len(bbb.shape))

2

In [54]:
a = torch.rand(2,3)
print(a)

tensor([[0.8395, 0.6763, 0.8405],
        [0.5207, 0.5044, 0.2841]])

In [55]:
print(a.shape)
print(a.size())
print(a.size(0))

torch.Size([2, 3])

torch.Size([2, 3])

2

In [57]:
a = torch.rand(4,2,3)
print(a)

tensor([[[0.6091, 0.1240, 0.4604],
         [0.6473, 0.8583, 0.8034]],

        [[0.8464, 0.8006, 0.8120],
         [0.8649, 0.0816, 0.1948]],

        [[0.0245, 0.6664, 0.0948],
         [0.2270, 0.6828, 0.6778]],

        [[0.8440, 0.1083, 0.5759],
         [0.5893, 0.1193, 0.9158]]])

In [64]:
a = torch.rand(32,3,64,64)
#[b,c,w,,h]

In [65]:
print(a.size(0))

32

In [66]:
#32*3*64*64
a.numel()

393216

In [67]:
a.dim()

4