In [1]:
import numpy as np
import torch

In [2]:
a = np.array([2,3.3])
print(a)

[2.  3.3]

In [3]:
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [4]:
a = np.ones([2,3])
print(torch.from_numpy(a))

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [6]:
#小写tensor接收现成数据
torch.tensor([2,3.3])

tensor([2.0000, 3.3000])

In [9]:
#大写Tensor/FloatTensor接收的是维度
#torch.FloatTensor(d1,d2,d3,....)
torch.FloatTensor(2,3)
#用List传入现有数据
torch.FloatTensor([2,3])

tensor([2., 3.])

In [10]:
torch.tensor([[1,2],[2,3]])

tensor([[1, 2],
        [2, 3]])

In [12]:
torch.empty(1)

tensor([0.])

In [13]:
torch.rand(3,3)

tensor([[0.9549, 0.0589, 0.8374],
        [0.8324, 0.6140, 0.8027],
        [0.5606, 0.7619, 0.8004]])

In [14]:
a = torch.rand(3,3)
print(a)

tensor([[0.3664, 0.1763, 0.8033],
        [0.8805, 0.3817, 0.6227],
        [0.2078, 0.7887, 0.0227]])

In [15]:
b = torch.rand_like(a)
print(b)

tensor([[0.4344, 0.0049, 0.4316],
        [0.4709, 0.0543, 0.3854],
        [0.7248, 0.2419, 0.7578]])

In [16]:
#torch.randint(low,high,size)
torch.randint(1,10,[3,3])

tensor([[7, 4, 1],
        [4, 2, 2],
        [7, 7, 4]])

In [17]:
torch.randn(3,3)

tensor([[ 1.1002, -2.3300, -0.5279],
        [ 0.9149, -1.1574,  0.8524],
        [ 0.2686,  0.0094,  0.4810]])

In [18]:
torch.full([2,3],7)

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [19]:
torch.full([],7)

tensor(7.)

In [20]:
torch.full([1],7)

tensor([7.])

In [21]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [24]:
torch.range(0,10)

F:\anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [3]:
#等分切割
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [28]:
torch.linspace(0,10,11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
#对数刻度均匀间隔的steps个点
torch.logspace(0,-1,11)

tensor([1.0000, 0.7943, 0.6310, 0.5012, 0.3981, 0.3162, 0.2512, 0.1995, 0.1585,
        0.1259, 0.1000])

In [32]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [37]:
#对角
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [38]:
a = torch.zeros(3,3)
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [39]:
#洗牌  [0,10)
torch.randperm(10)

tensor([4, 9, 7, 6, 5, 8, 2, 0, 3, 1])

In [40]:
a = torch.rand(2,3)
b = torch.rand(2,2)

In [41]:
a,b

(tensor([[0.0578, 0.9522, 0.2778],
         [0.7954, 0.5007, 0.8952]]), tensor([[0.6590, 0.3408],
         [0.0609, 0.6338]]))

In [45]:
#idx作为洗牌的索引
idx = torch.randperm(2)
print(idx)

tensor([1, 0])

In [53]:
print(a[1,2])
print(a[1][2])

tensor(0.8952)

tensor(0.8952)

In [55]:
a[idx],b[idx]

(tensor([[0.7954, 0.5007, 0.8952],
         [0.0578, 0.9522, 0.2778]]), tensor([[0.0609, 0.6338],
         [0.6590, 0.3408]]))