In [1]:
import torch
import numpy as np

In [2]:
a = torch.rand(4,3,28,28)

In [3]:
a[0].shape

torch.Size([3, 28, 28])

In [4]:
a[0,0].shape

torch.Size([28, 28])

In [6]:
a[0,0,2,4]

tensor(0.8935)

In [7]:
#前两张[0,2)图片的维度
a[:2].shape

torch.Size([2, 3, 28, 28])

In [8]:
a[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

In [3]:
a[:2,:-1,:,:].shape

torch.Size([2, 2, 28, 28])

In [4]:
a[:,:-1,...].shape

torch.Size([4, 2, 28, 28])

In [10]:
#[0,28)隔2个点采样
a[:,:,0:28:2,0:28:2].shape

torch.Size([4, 3, 14, 14])

In [11]:
#::1  与 :相同
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

In [15]:
a = torch.rand(3,4)
print(a)

tensor([[0.1779, 0.5599, 0.9040, 0.3693],
        [0.9656, 0.6030, 0.1176, 0.5272],
        [0.1758, 0.3204, 0.4419, 0.5758]])

In [27]:
#index_select   传入为 dim,[1,2,3,...]
indices = torch.LongTensor([1,2])
a.index_select(1,indices)
# print(indices)

tensor([[0.5599, 0.9040],
        [0.6030, 0.1176],
        [0.3204, 0.4419]])

In [29]:
a = torch.rand(4,3,28,28)
a.index_select(2,torch.arange(0,28,2)).shape

torch.Size([4, 3, 14, 28])

In [31]:
#...取所有dim   相当于[:,:,:]
a[...].shape

torch.Size([4, 3, 28, 28])

In [32]:
a[1,...].shape

torch.Size([3, 28, 28])

In [33]:
a[:,1,...].shape

torch.Size([4, 28, 28])

In [35]:
a[...,:2].shape

torch.Size([4, 3, 28, 2])

In [37]:
x = torch.rand(3,4)
print(x)

tensor([[0.0448, 0.3076, 0.0626, 0.6524],
        [0.9834, 0.5784, 0.3222, 0.0821],
        [0.3455, 0.8766, 0.1700, 0.7412]])

In [38]:
#比0.5大的
mask = x.ge(.5)
print(mask)

tensor([[0, 0, 0, 1],
        [1, 1, 0, 0],
        [0, 1, 0, 1]], dtype=torch.uint8)

In [39]:
torch.masked_select(x,mask)

tensor([0.6524, 0.9834, 0.5784, 0.8766, 0.7412])

In [40]:
torch.masked_select(x,mask).shape

torch.Size([5])

In [43]:
src = torch.tensor([[4,3,5],[6,7,8]])
torch.take(src,torch.tensor([0,2,3]))

tensor([4, 5, 6])