In [1]:
import torch

In [2]:
#4张28*28的灰度图
a = torch.rand(4,1,28,28)
a.shape

torch.Size([4, 1, 28, 28])

In [3]:
#4行 每行为每张图片的所有像素点  适用于全连接层
a.view(4,1*28*28)

tensor([[0.2223, 0.8020, 0.3510,  ..., 0.7702, 0.8769, 0.3944],
        [0.4540, 0.2450, 0.0769,  ..., 0.1546, 0.1524, 0.4880],
        [0.2385, 0.3541, 0.6435,  ..., 0.6591, 0.6361, 0.8827],
        [0.1826, 0.0189, 0.3511,  ..., 0.6050, 0.0476, 0.2301]])

In [4]:
a.view(4,1*28*28).shape

torch.Size([4, 784])

In [7]:
#所有图片竖着排在一起
a.view(4*1*28,28).shape

torch.Size([112, 28])

In [8]:
#将所有图的通道都堆在一起 比如4张图每张3通道 -> 12张28*28的特征图 不管管特征图是哪张图的哪张通道
a.view(4*1,28,28).shape

torch.Size([4, 28, 28])

In [10]:
a = torch.rand(4,3,28,28)
a.shape

torch.Size([4, 3, 28, 28])

In [11]:
a.unsqueeze(0).shape

torch.Size([1, 4, 3, 28, 28])

In [12]:
a.unsqueeze(-1).shape

torch.Size([4, 3, 28, 28, 1])

In [14]:
a.unsqueeze(-4).shape

torch.Size([4, 1, 3, 28, 28])

In [15]:
a = torch.tensor([1.2,2.3])#dim 2

In [18]:
a.unsqueeze(-1)#dim变成[2,1]

tensor([[1.2000],
        [2.3000]])

In [19]:
a.unsqueeze(0)#dim变成[1,2]

tensor([[1.2000, 2.3000]])

In [20]:
b = torch.rand(32)
b.unsqueeze(1).unsqueeze(2).unsqueeze(0).shape

torch.Size([1, 32, 1, 1])

In [21]:
#sequeeze()

In [27]:
b = torch.rand(32)
b.unsqueeze(1).unsqueeze(2).unsqueeze(0).shape


torch.Size([1, 32, 1, 1])

In [28]:
b.squeeze().shape

torch.Size([32])

In [39]:
b = torch.rand(1,32,1,1)
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [40]:
#挤压不了
b = torch.rand(1,32,1,1)
b.squeeze(1).shape

torch.Size([1, 32, 1, 1])

In [ ]:
b = torch.rand(1,32,1,1)
b.shape

In [ ]:
#只有dim为1的可以扩展
b.expand(4,32,14,14).shape

In [44]:
#-1表示该处维度不变
b.expand(4,32,-1,-1).shape

torch.Size([4, 32, 1, 1])

In [45]:
b = torch.rand(1,32,1,1)
b.shape

torch.Size([1, 32, 1, 1])

In [47]:
b.repeat(4,32,1,1).shape

torch.Size([4, 1024, 1, 1])