In [1]:
import torch

In [2]:
a = torch.rand(3,4)
b = torch.rand(4)
a,b

(tensor([[0.1207, 0.0887, 0.6575, 0.1346],
         [0.6373, 0.2629, 0.5209, 0.7482],
         [0.5751, 0.4385, 0.7416, 0.8855]]),
 tensor([0.9858, 0.2843, 0.8752, 0.6873]))

In [3]:
a+b

tensor([[1.1065, 0.3730, 1.5326, 0.8219],
        [1.6231, 0.5473, 1.3960, 1.4355],
        [1.5609, 0.7229, 1.6168, 1.5728]])

In [4]:
torch.add(a,b)

tensor([[1.1065, 0.3730, 1.5326, 0.8219],
        [1.6231, 0.5473, 1.3960, 1.4355],
        [1.5609, 0.7229, 1.6168, 1.5728]])

In [6]:
# torch.sub(a,b)  
# torch.mul(a,b) 
# torch.div(a,b)

In [7]:
a = torch.full([2,2],3)
b = torch.ones(2,2)
a,b

(tensor([[3., 3.],
         [3., 3.]]), tensor([[1., 1.],
         [1., 1.]]))

In [8]:
torch.mm(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [9]:
torch.matmul(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [10]:
a@b

tensor([[6., 6.],
        [6., 6.]])

In [11]:
x = torch.rand(4,784)
w = torch.rand(512,784)
(x@w.t()).shape

torch.Size([4, 512])

In [12]:
a = torch.rand(4,3,28,64)
b = torch.rand(4,3,64,32)
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])

In [14]:
#dim=2处自动broadcasting
b = torch.rand(4,1,64,32)
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])

In [16]:
a = torch.full([2,2],3)
a

tensor([[3., 3.],
        [3., 3.]])

In [17]:
a.pow(2)

tensor([[9., 9.],
        [9., 9.]])

In [19]:
aa = a**2
aa

tensor([[9., 9.],
        [9., 9.]])

In [20]:
aa.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [21]:
aa**.5

tensor([[3., 3.],
        [3., 3.]])

In [22]:
#平方根倒数
aa.rsqrt()

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [23]:
a = torch.exp(torch.ones((2,2)))
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [24]:
torch.log(a)

tensor([[1., 1.],
        [1., 1.]])

In [25]:
a = torch.tensor(3.14)

In [26]:
a.floor(),a.ceil()

(tensor(3.), tensor(4.))

In [28]:
#取整数部分，取小数部分
a.trunc(),a.frac()

(tensor(3.), tensor(0.1400))

In [32]:
 # 四舍五入
a = torch.tensor(3.499)
a.round()

tensor(3.)

In [33]:
a = torch.tensor(3.5)
a.round()

tensor(4.)

In [35]:
grad = torch.rand(2,3)*15
grad

tensor([[12.6394,  9.9873, 11.8612],
        [ 4.9036,  2.9613,  9.1861]])

In [36]:
grad.clamp(min=10)

tensor([[12.6394, 10.0000, 11.8612],
        [10.0000, 10.0000, 10.0000]])

In [39]:
grad.clamp(max=11)

tensor([[11.0000,  9.9873, 11.0000],
        [ 4.9036,  2.9613,  9.1861]])

In [40]:
grad.clamp(min=10,max=11)

tensor([[11., 10., 11.],
        [10., 10., 10.]])