In [1]:
import torch

In [2]:
a = torch.full([8],1)
a

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
b = a.view(2,4)
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
c = a.view(2,2,2)
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [5]:
#1范数 绝对值之和
a.norm(1),b.norm(1),c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [11]:
#2范数 平方和开根号
a.norm(2),b.norm(2),c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [15]:
#指定维度的范数
b.norm(1,dim=1)

tensor([4., 4.])

In [6]:
c = torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]]])
c

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [7]:
c.shape

torch.Size([2, 2, 2])

In [9]:
#dim=d d维就不要了 好好领会
c.norm(1,dim=0)
# c.norm(1,dim=0).shape
# c.norm(1,dim=1)
# c.norm(1,dim=2)

tensor([[ 6.,  8.],
        [10., 12.]])

In [34]:
a = torch.arange(start=0,end=8).view(2,4).float()
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [35]:
#prod()是累乘
a.min(),a.max(),a.mean(),a.prod()

(tensor(0.), tensor(7.), tensor(3.5000), tensor(0.))

In [36]:
a.sum()

tensor(28.)

In [37]:
先打平再找索引
a.argmax(),a.argmin()

(tensor(7), tensor(0))

In [39]:
a.argmax(0)

tensor([1, 1, 1, 1])

In [40]:
a = torch.randn(4,10)
a

tensor([[ 0.5674,  0.6023, -0.0973, -0.1624,  0.6286, -0.1252, -2.0766, -0.1370,
          0.8243, -0.4091],
        [-0.4765, -0.1351,  0.4115,  1.9592, -1.0903,  0.4019, -0.2477, -0.6964,
          0.5397, -0.8584],
        [-2.5049, -0.3341,  0.5151, -1.5122, -0.3855,  0.1458,  0.0042, -0.6415,
          0.3954, -1.5193],
        [ 0.0057, -0.1929,  3.4300, -0.7203, -0.0192, -0.3114, -0.1111, -1.3583,
         -0.5178,  0.3166]])

In [41]:
a.max(dim=1)#不要列了

torch.return_types.max(
values=tensor([0.8243, 1.9592, 0.5151, 3.4300]),
indices=tensor([8, 3, 2, 2]))

In [42]:
a.argmax(dim=1)

tensor([8, 3, 2, 2])

In [44]:
a.max(dim=1,keepdim=True)#返回维度[4,1]和[4,1]

torch.return_types.max(
values=tensor([[0.8243],
        [1.9592],
        [0.5151],
        [3.4300]]),
indices=tensor([[8],
        [3],
        [2],
        [2]]))

In [45]:
a.argmax(dim=1,keepdim=True)

tensor([[8],
        [3],
        [2],
        [2]])

In [46]:
a = torch.randn(4,10)
a

tensor([[ 0.0226,  0.8846,  1.5540, -0.2267,  0.1072,  1.7523,  0.1904, -0.5233,
          1.5384,  0.4485],
        [-0.5975, -0.4456,  1.0994, -0.9228,  0.1726, -0.4335, -1.7082,  0.4348,
          1.1659, -0.4506],
        [-0.2072,  0.8914, -1.3725, -1.1161,  0.7547,  2.0322, -0.3240,  1.0329,
         -0.9314, -0.0952],
        [-0.5081,  1.3224,  1.6256,  0.6532,  0.8584, -0.2027, -0.9174, -0.9072,
         -0.1442, -0.9411]])

In [47]:
a.topk(k=3,dim=1)

torch.return_types.topk(
values=tensor([[1.7523, 1.5540, 1.5384],
        [1.1659, 1.0994, 0.4348],
        [2.0322, 1.0329, 0.8914],
        [1.6256, 1.3224, 0.8584]]),
indices=tensor([[5, 2, 8],
        [8, 2, 7],
        [5, 7, 1],
        [2, 1, 4]]))

In [48]:
#前三小的
a.topk(3,1,False)

torch.return_types.topk(
values=tensor([[-0.5233, -0.2267,  0.0226],
        [-1.7082, -0.9228, -0.5975],
        [-1.3725, -1.1161, -0.9314],
        [-0.9411, -0.9174, -0.9072]]),
indices=tensor([[7, 3, 0],
        [6, 3, 0],
        [2, 3, 8],
        [9, 6, 7]]))

In [49]:
#第k小
a.kthvalue(8,dim=1)

torch.return_types.kthvalue(
values=tensor([1.5384, 0.4348, 0.8914, 0.8584]),
indices=tensor([8, 7, 1, 4]))

In [50]:
a = torch.randn(3,4)
a

tensor([[-0.9594,  0.3238, -0.2984, -1.0087],
        [ 2.6842, -1.3041, -0.2976,  0.3517],
        [ 0.8897,  0.7598,  0.3028,  0.0779]])

In [51]:
#  > < >= <= != ==
a>0

tensor([[0, 1, 0, 0],
        [1, 0, 0, 1],
        [1, 1, 1, 1]], dtype=torch.uint8)

In [52]:
torch.gt(a,0)#== a>0

tensor([[0, 1, 0, 0],
        [1, 0, 0, 1],
        [1, 1, 1, 1]], dtype=torch.uint8)

In [54]:
a = torch.ones(2,3)
b = torch.randn(2,3)
torch.eq(a,b)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

In [55]:
torch.eq(a,a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [56]:
torch.equal(a,a)

True