In [1]:
import torch

In [2]:
condition = torch.rand(2,2)
condition

tensor([[0.2764, 0.1012],
        [0.3149, 0.9394]])

In [3]:
a = torch.zeros(2,2)
b = torch.ones(2,2)
a,b

(tensor([[0., 0.],
         [0., 0.]]), tensor([[1., 1.],
         [1., 1.]]))

In [4]:
torch.where(condition>0.5,a,b)

tensor([[1., 1.],
        [1., 0.]])

In [6]:
prob = torch.randn(4,10)
prob

tensor([[-0.3849,  0.6629,  0.2768, -0.3214,  2.5108, -0.9202, -0.1336, -0.2436,
         -1.0793,  0.8956],
        [-0.2562,  0.1056, -1.6957,  0.6380, -2.0201, -0.5975,  0.8315,  0.1165,
         -1.4352,  0.0388],
        [ 0.9098, -0.9617, -0.7135, -0.0785, -0.0200,  0.5812, -1.9131, -1.4391,
         -0.0736, -1.1560],
        [ 0.8999, -0.0186, -0.9111, -0.2860,  0.0645, -0.6413, -0.1403, -1.9025,
          0.6210,  0.1224]])

In [14]:
idx = prob.topk(k=3,dim=1)
idx

torch.return_types.topk(
values=tensor([[ 2.5108,  0.8956,  0.6629],
        [ 0.8315,  0.6380,  0.1165],
        [ 0.9098,  0.5812, -0.0200],
        [ 0.8999,  0.6210,  0.1224]]),
indices=tensor([[4, 9, 1],
        [6, 3, 7],
        [0, 5, 4],
        [0, 8, 9]]))

In [ ]:
idx = idx[1]
idx

In [18]:
label = torch.arange(10)+100
label = label.expand(4,10)
label

tensor([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [19]:
torch.gather(label,dim=1,index=idx.long())

tensor([[104, 109, 101],
        [106, 103, 107],
        [100, 105, 104],
        [100, 108, 109]])