In [2]:
import torch
import torch.nn as nn

In [3]:
net = nn.Sequential(nn.Linear(4,2),nn.Linear(2,2))

In [5]:
#l0.w的维度  输出在前
list(net.parameters())[0].shape

torch.Size([2, 4])

In [6]:
#l1.b
list(net.parameters())[3].shape

torch.Size([2])

In [8]:
list(net.named_parameters())[0]

('0.weight', Parameter containing:
 tensor([[-0.1449,  0.2442,  0.1841, -0.4396],
         [-0.3307, -0.1381,  0.0522, -0.1090]], requires_grad=True))

In [9]:
list(net.named_parameters())[1]

('0.bias', Parameter containing:
 tensor([-0.3022,  0.2665], requires_grad=True))

In [10]:
dict(net.named_parameters()).items()

dict_items([('0.weight', Parameter containing:
tensor([[-0.1449,  0.2442,  0.1841, -0.4396],
        [-0.3307, -0.1381,  0.0522, -0.1090]], requires_grad=True)), ('0.bias', Parameter containing:
tensor([-0.3022,  0.2665], requires_grad=True)), ('1.weight', Parameter containing:
tensor([[-0.1577,  0.5062],
        [ 0.4887, -0.3070]], requires_grad=True)), ('1.bias', Parameter containing:
tensor([0.5126, 0.3808], requires_grad=True))])

In [11]:
import torch.optim as optim

In [12]:
optimizer = optim.SGD(net.parameters(),lr=1e-3)

In [15]:
device = torch.device('cuda')
net = Net()
net.to(device)

NameError: name 'Net' is not defined

In [ ]:
net.load_state_dict(torch.load('ckpt.mdl'))
#train...
torch.save(net.state_dict(),'ckpt.mdl')

#-------------------------------------

In [16]:
class Flatten(nn.Module):
    def __init__(self):
        super(Flatten, self).__init__()
    def forward(self,input):
        return input.view(input.size(0),-1)

In [17]:
a = torch.rand(4,3,28,28)
a.shape

torch.Size([4, 3, 28, 28])

In [18]:
a.view(a.size(0),-1).shape

torch.Size([4, 2352])

In [20]:
a.view(a.size(0),a.size(1),-1).shape

torch.Size([4, 3, 784])

In [21]:
class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()
        self.net = nn.Sequential(
            nn.Conv2d(1,16,stride=1,padding=1),
            nn.MaxPool2d(2,2),
            Flatten(),
            nn.Linear(1*14*14,10)
        )
    def forward(self,x):
        return self.net(x)

In [22]:
class MyLinear(nn.Module):
    def __init__(self,inp,outp):
        super(MyLinear, self).__init__()
        
        #requires_grad = True 自动加载进net.parrameters中
        self.w = nn.Parameter(torch.randn(outp,inp))
        self.b = nn.Parameter(torch.randn(outp))
    def forward(self,x):
        return x@self.w.t()+self.b

In [25]:
import torchvision.transforms as transforms
from torchvision import datasets

train_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data',train=True,download=True,
                   transform = transforms.Compose(
                       [transforms.RandomHorizontalFlip(),
                        transforms.RandomVerticalFlip(),
                        transforms.RandomRotation(15),
                        #transforms.RandomRotation([90,180,270]),
                        transforms.Resize([32,32]),
                        transforms.RandomCrop([28,28]),
                        transforms.ToTensor(),
                       ])),
    batch_size = batch_size,shuffle = True)

0it [00:00, ?it/s]

  0%|                                                                                      | 0/9912422 [00:01<?, ?it/s]

  1%|▋                                                                     | 98304/9912422 [00:01<00:10, 964944.35it/s]

  2%|█▌                                                                  | 221184/9912422 [00:01<00:09, 1026412.04it/s]

  4%|███                                                                 | 442368/9912422 [00:01<00:07, 1222838.76it/s]

  7%|█████                                                               | 729088/9912422 [00:01<00:06, 1470263.46it/s]

 11%|███████▋                                                           | 1138688/9912422 [00:01<00:04, 1817607.03it/s]

 14%|█████████▎                                                         | 1376256/9912422 [00:01<00:04, 1894885.61it/s]

 20%|█████████████▍                                                     | 1990656/9912422 [00:01<00:03, 2357784.17it/s]

 24%|████████████████▍                                                  | 2424832/9912422 [00:01<00:02, 2730369.33it/s]

 29%|███████████████████                                                | 2826240/9912422 [00:01<00:02, 2986959.56it/s]

 33%|██████████████████████▏                                            | 3284992/9912422 [00:02<00:02, 3307688.98it/s]

 37%|████████████████████████▊                                          | 3678208/9912422 [00:02<00:01, 3246551.95it/s]

 42%|████████████████████████████▏                                      | 4169728/9912422 [00:02<00:01, 3575558.68it/s]

 47%|███████████████████████████████▍                                   | 4653056/9912422 [00:02<00:01, 3869748.70it/s]

 51%|██████████████████████████████████▎                                | 5079040/9912422 [00:02<00:01, 3946500.29it/s]

 56%|█████████████████████████████████████▏                             | 5505024/9912422 [00:02<00:01, 4006686.24it/s]

 60%|████████████████████████████████████████                           | 5931008/9912422 [00:02<00:00, 4068414.89it/s]

 64%|███████████████████████████████████████████                        | 6373376/9912422 [00:02<00:00, 4146084.97it/s]

 69%|█████████████████████████████████████████████▉                     | 6799360/9912422 [00:02<00:00, 3957618.91it/s]

 73%|█████████████████████████████████████████████████                  | 7249920/9912422 [00:03<00:00, 4088079.85it/s]

 77%|███████████████████████████████████████████████████▊               | 7667712/9912422 [00:03<00:00, 3564785.63it/s]

 83%|███████████████████████████████████████████████████████▎           | 8192000/9912422 [00:03<00:00, 3935061.79it/s]

 87%|██████████████████████████████████████████████████████████▏        | 8609792/9912422 [00:03<00:00, 3994088.86it/s]

 91%|█████████████████████████████████████████████████████████████      | 9027584/9912422 [00:03<00:00, 3967507.74it/s]

 95%|███████████████████████████████████████████████████████████████▊   | 9437184/9912422 [00:03<00:00, 3982504.08it/s]

 99%|██████████████████████████████████████████████████████████████████▌| 9846784/9912422 [00:03<00:00, 4004794.74it/s]

9920512it [00:03, 2666267.53it/s]                                                                                      

Extracting ../data\MNIST\raw\train-images-idx3-ubyte.gz

0it [00:00, ?it/s]

  0%|                                                                                        | 0/28881 [00:04<?, ?it/s]

KeyboardInterrupt: 